name: Deploy React App to VPS

on:
  push:
    branches:
      - main  # Укажите ветку, которую хотите отслеживать

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.0.0  # Укажите версию Node.js

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 4: Сборка приложения
      - name: Build the project
        run: npm run build

      # Шаг 5: Проверка содержимого папки dist
      - name: List dist files
        run: ls -R dist

      # Шаг 6: Копирование файлов на VPS
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.IP_ADRESS }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/"  # Указываем папку dist
          target: "/var/www/html/client-agencyGIR"

      # Шаг 7: Перезапуск Nginx (опционально)
